version: "3"

services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SENGRID_API_KEY: ${SENGRID_API_KEY}
      SENGRID_EMAIL_FROM: ${SENGRID_EMAIL_FROM}
      SENGRID_DEFAULT_REPLY: ${SENGRID_DEFAULT_REPLY}
      SENGRID_TEST_ACCOUNT: ${SENGRID_TEST_ACCOUNT}
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/data/db
  
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
